version: 2.0

jobs:
    build:
        docker:
            - image: circleci/openjdk:9-jdk
        steps:
            - checkout
            - restore_cache:
                keys:
                    - gradle-{{ checksum "build.gradle" }}
            - run: gradle build
            - store_artifacts:
                path:  build/reports
            - save_cache:
                paths:
                    - ~/.gradle
                key: gradle-{{ checksum "build.gradle" }}
